### PR TITLE
Better handling error when not available

### PR DESCRIPTION
**Pull request by riderx**
Add callback for valid and error scenarios.
Allow user to refuse and then accept recording without issue
Allow users to set mic after they refuse the first time .
this code is tested and used there : https://github.com/riderx/capacitor-screen-recorder

### CODE REVIEW

**Comment by aehlke** [comment]
@toupper can you please merge or add more people as maintainers to this project? :) thanks

**Comment by toupper** [comment]
@aehlke Thanks for the ping here! I added you as collaborator, there're some conflicts in this PR, would you like to fix them and merge this PR if you have time?

**Comment by riderx** [comment]
I can fix my own conflict ^^

**Comment by toupper** [comment]
> I can fix my own conflict ^^

That would be awesome, thanks @riderx! Let me know when it's done so I can merge it :)

**Comment by riderx** [comment]
should be good

**Comment by toupper** [comment]
Awesome, thanks @riderx

**Pull request merged**
